<?php



/**
*
* Implementation of hook_menu().
*
*/



function davinder_menu() {

    $menuitems['davinder'] = array(

    'title' => 'My Menu',

    'page callback' => 'davinder_mymenu_page_callback',

    'access callback' => TRUE,

    'type' => MENU_CALLBACK,

    );
$menuitems['snehi'] = array(

    'title' => 'My Menu',

    'page callback' => 'snehi_mymenu_page_callback',

    'access callback' => TRUE,

    'type' => MENU_CALLBACK,

    );
    return $menuitems;

}

function davinder_mymenu_page_callback() {


    return 'My Menu URL was hit';

}
function snehi_mymenu_page_callback() {
  return 'i am snehi';
}


?>
